name: JawaCommands
main: jawamaster.jawacommands.JawaCommands
description: "A command plugin to make minecraft a little more user friendly"
version: 1.2
api-version: 1.16
depends: JawaPermissions, JawaCore
commands:
  home:
    description: Used for home control.
    usage: '/home <[d|sr|s|i|l|h]> <homename>'
    permission: jawacommands.home
  homeinfo:
    description: Provides a user with specific home information
    usage: /homeinfo <homename>
    permission: jawacommands.home.info
  sudo:
    description: Allows an administrative user to force a regular user to run a command.
    permission: jawacommands.sudo
  warp:
    description: Warps a player to a specified warp.
    usage: '/warp <warp> [other|@p|@a] [override]'
    permission: jawacommands.warps.warp
  makewarp:
    description: 'Creates a warp.'
    permission: jawacommands.warps.create
  modwarp:
    description: Modifies a warp.
    usage: '/modwarp <warpname> [whitelist|location|hidden|owner|type] <[owner|type]>'
    permission: jawacommands.warps.modify
  warpinfo:
    description: Displayer relevent warp information.
    usage: '/warpinfo <warpname>'
    permission: jawacommands.warps.info
  delwarp:
    description: Deletes a warp.
    permission: jawacommands.warps.delete
  wlwarp:
    usage: '/wlwarp <warp name> <add|remove> <player name|selector>'
    description: Add/remove a user or users to the whitelist
  blwarp:
    description: Adds a player to the warps blacklist
  gm:
    description: Changes a player's game mode.
    permission: gamemode.toggle
  spawn:
    description: Send a player to the corresponding world's spawn
    permission: jawacommands.spawn
  setspawn:
    description: Sets the spawn location of a world.
    permission: jawacommands.setspawn
  gothere:
    description: Asks a player if you can teleport to them
    permission: jawacommands.gothere
  comehere:
    description: Asks a player to teleport to you
    permission: jawacommands.comehere
  accept:
    description: Accepts a teleport request
    permission: jawacommands.accept
  fullbright:
    description: Gives you nightvision
    permission: jawacommands.fullbright
  removespawn:
    description: Removes a custom spawn
    permission: jawacommands.spawn.remove
  kit:
    description: 'Used to create, modify, and give kits'
    permission: jawacommands.kit.user
    usage: 'Run /kit for full instructions'
  givekit:
    description: 'Used to give a kit to a player by staff, commandblock, or console'
    permission: jawacommands.kit.other
    usage: 'Run /givekit for full instructions'
  yeetport:
    description: 'Yeets a player into the air before teleporting to a warp'
    permission: jawacommands.yeetport
  back:
    description: 'sends you back to the last teleport location'
    permission: jawacommands.back
  colors:
    description: 'sends a message to the player containing all of the color names and char codes as they appear in the code'
    usage: '/colors'
  testcommand:
    description: Does whatever whenever i use it
    usage: test usage
  tpr:
    description: Randomly teleports a target
    usage: '/tpr [target]'
  freeze:
    description: "Freezes a player's motion preventing them from moving"
    usage: "/freeze <player>"
    permission: jawacommands.freeze
  pweather:
    description: "Allows a player to toggle their local player weather"
    usage: "/pweather [clear|rain|reset] [player]. Run without arguments to reset your own weather."
    permission: "jawacommands.pweather"
  ptime:
    description: "Allows a player to toggle their local player time"
    usage: "/ptime [morning|noon|sunset|night|midnight|sunrise|reset] [player]. Run without arguments to reset your own weather."
    permission: "jawacommands.ptime"
  sfly:
    description: "Allows a survival player to enable flight for themselves"
    usage: "/sfly"
    permission: "jawacommands.sfly"
  flyspeed:
    description: Sets a player's flying speed
    usage: "/flyspeed <[1|2|3|4|6|8|10]>"
    permission: "jawacommands.flyspeed"
  walkspeed:
    description: Sets a player's walk speed
    usage: "/walkspeed <[1|2|3|4|5|6|7|8|9|10]>"
    permission: "jawacommands.walkspeed"
  otherhome:
    description: View another player's home data
    usage: "/otherhome <player name> <[info|homename]> <[homename]>"
    permission: "jawacommands.home.other"
  repair:
    description: Repair the item held in hand
    usage: "/repair"
    permission: "jawacommands.items.repair"
    
    
permissions:
  jawacommands.back:
      description: Allows back command
      default: true
  jawacommands.yeetport:
      description: Allows a player to trugger a yeetport
      default: op
  jawacommands.kit.user:
      description: Allows a user to use the kit command
      default: false
  jawacommands.kit.admin:
      description: Allows admin access to the kit command
      default: op
  jawacommands.kit.other:
      description: Allows admin access to the givekit command
      default: op
  jawacommands.spawn.remove:
      description: Allows a user to remove a spawn
      default: false
  jawacommands.fullbright:
      description: Allows a user to use fullbright
      default: true
  jawacommands.accept:
      description: Allows a user to accept tp requests
      default: true
  jawacommands.comehere:
      description: Allows a user to ask a player to teleport to them
      default: true
  jawacommands.gothere:
      description: Allows a user to ask a player if they can teleport to them
      default: true
  jawacommands.setspawn:
      description: Allows an admin to create a specific spawn
      default: true
  jawacommands.spawn:
      description: Allows a user to go to spawn
      default: true
  gamemode.toggle:
      description: Allows a user to toggle between gamemodes
      default: true
  jawacommands.warps.blacklist:
      description: Allows an admin to add a black list to a warp
      default: op
  jawacommands.warps.whitelist:
      description: Allows an admin to add a white list to a warp
      default: op
  jawacommands.warps.delete:
      description: Allows an admin to delete a warp
      default: op
  jawacommands.warps.modify:
      description: Allows an admin to add modify a warp
      default: op
  jawacommands.warps.create:
      description: Allows an admin to create a warp
      default: op
  jawacommands.warps.warp:
      description: Allows a player to list warps they can see and visit them
      default: true
  jawacommands.warps.info:
      description: Allows a player to see information regarding a warp
      default: true
  jawacommands.sudo:
      description: Allows an admin to force a player to run a command
      default: op
  jawacommands.home.info:
      description: Allows an player to see their home info
      default: true
  jawacommands.home.add:
      description: Allows an player to add a home
      default: true
  jawacommands.home.list:
      description: Allows an player to list their homes
      default: true
  jawacommands.home.del:
      description: Allows an player to delete a home
      default: true
  jawacommands.home.set:
      description: Allows an player to set homes
      default: true
  jawacommands.home:
      description: Allows an player to access the generalized home command
      default: true
  jawacommands.freeze:
      description: Allows an admin to freeze or thaw a player with the freeze command
      default: op
  jawacommands.pweather:
      description: "Allows a user to change their local player weather"
      default: true
  jawacommands.pweather.other: 
      description: "Allows an admin to control the weather of another user"
      default: op
  jawacommands.ptime:
      description: "Allows a user to change their local player time"
      default: true
  jawacommands.ptime.other:
      description: "Allows an admin to control the time of another user"
      default: op
  jawacommands.sfly:
      description: "Allows a player to enable flight for themselves"
      default: op
  jawacommands.flyspeed:
      description: "Allows a player to set their fly speed"
      default: op
  jawacommands.walkspeed:
      description: "Allows a player to set their walk speed"
      default: op
  jawacommands.home.other:
      description: "Allows staff to view/tp to another player's homes"
      default: op
  jawacommands.items.repair:
      description: "Allows a user to repair the item in hand"
      default: op